server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: hobbiedo-gateway-service

  output:
    ansi:
      enabled: always

  cloud:
    gateway:
      routes:

        - id: auth-service-need-not-token
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/v1/**
            - Method=POST
          filters:
            #- StripPrefix=1
            - RemoveRequestHeader=Cookie
            - StripPrefix=1

        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/v1/**
            - Method=GET, POST, PUT, DELETE, PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
            - JwtTokenFilter

jwt:
  secret: 25c4798333e340171ef525ff3729fd89880331acf2bc899656d27802f56768b03f6cd6fc835725f7796f88040eeac6be2af212f124ee5f44a68a61aeda87e789